### ISSUE TITLE
Create stand alone common module

### ISSUE THREAD

**Issue by elshanakberov** [AlicanAkkus/Modular-Architecture-Hexagonal-Demo-Project#12]
**It's neither bug nor feature but would definitely eliminate code duplication**

In each services there're **common sub-modules** for both domain and infra. Certain classes, interfaces and enums such as Event, Status, UseCase, UseCaseHandler are repeatedly created. Considering addition of several other microservices to the project, it'll definitely increase the code repetition. 

It'd be a better implementation to separate **common module** to an individual one. Such as 

```

\common
      \ domain 
             \ commandhandler
                    CommandHandler
      \ infra
             \ entity
                    AbstractEntity
\payment-api
\ticket-api
...
```
P.s I'm planning to make a PR for this matter if the issue is also okay with you guys.

**Comment by lemiorhan** [comment]
Common modules are evil 😄 From what I experienced in 20 years of programming, the requirements in different modules push the developers to change the common module with lots of hacky implementations. Even, if you maintain common modules so long, you will see developers start to copy the code into their modules to freely change the internals.

Code reuse increases coupling to some extend. Therefore DRY principle could be dangerous in some cases. 

We have a golden rule in our projects. 10-20% code duplication among modules is all fine and we never use a common module at all. Here, your observation is 100% correct, but it is done by purpose. Thanks a lot for your suggestion and time for improving the project. 🙏🏻

**Comment by lemiorhan** [comment]
I am closing the ticket since we are against common modules for the sake of loose-coupling. Thanks again for your kind explanation and suggestion. Very appreciated.

**Comment by elshanakberov** [comment]
Thank you for your broad explanation @lemiorhan . Your point made me think about the topic. I appreciate your time and effort.
